%YAML:1.0
calibration_time: "12/27/16 15:49:19"
nrOfFrames: 25
image_width: 640
image_height: 480
board_width: 9
board_height: 6
square_size: 26.
FixAspectRatio: 1.
# flags:  +fix_aspectRatio +fix_principal_point +zero_tangent_dist
flagvalue: 14
camera_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 7.1748364317208518e+002, 0., 3.1950000000000000e+002, 0.,
       7.1748364317208518e+002, 2.3950000000000000e+002, 0., 0., 1. ]
distortion_coefficients: !!opencv-matrix
   rows: 5
   cols: 1
   dt: d
   data: [ -7.9198437829050977e-002, -3.4815582531751482e-001, 0., 0.,
       1.7966793092750946e+000 ]
avg_reprojection_error: 8.6610765340599327e-001